/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.entity.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.tuwien.big.forms.entity.ui.internal.EntityActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EntityExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EntityActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EntityActivator.getInstance().getInjector(EntityActivator.AT_AC_TUWIEN_BIG_FORMS_ENTITY_ENTITY);
	}
	
}
