/**
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.entity.validation;

import at.ac.tuwien.big.forms.entity.validation.AbstractEntityValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class EntityValidator extends AbstractEntityValidator {
}
