/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.entity.ui.contentassist

import at.ac.tuwien.big.forms.entity.ui.contentassist.AbstractEntityProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EntityProposalProvider extends AbstractEntityProposalProvider {
}
