/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.form;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FormRuntimeModule extends at.ac.tuwien.big.forms.form.AbstractFormRuntimeModule {

}
