/*
* generated by Xtext
*/
package at.ac.tuwien.big.forms.form;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FormStandaloneSetup extends FormStandaloneSetupGenerated{

	public static void doSetup() {
		new FormStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

