/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.entity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityUiModule extends at.ac.tuwien.big.forms.entity.ui.AbstractEntityUiModule {
	public EntityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
