/**
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.form.validation;

import at.ac.tuwien.big.forms.form.validation.AbstractFormValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class FormValidator extends AbstractFormValidator {
}
