/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.form.ui.contentassist

import at.ac.tuwien.big.forms.form.ui.contentassist.AbstractFormProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FormProposalProvider extends AbstractFormProposalProvider {
}
