/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.entity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityRuntimeModule extends at.ac.tuwien.big.forms.entity.AbstractEntityRuntimeModule {

}
